### ISSUE TITLE
Discussion topic for Sprint 0

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#203]
This issue will include topics we want to discuss and decide during the planning phase
The point is to keep an organized list of topics and to open relevant issues with tasks by the end of the sprint

1. Logging solution, possibly :
1.1. [Log4j ](https://logging.apache.org/log4j/2.0/) / [Logback](https://logback.qos.ch/) ?
1.2. [Graylog ](https://www.graylog.org/)as both a viewer and a log unification system
2. Complete refactoring of the Database classes
2.1. Using [RxJava](http://reactivex.io/)?
2.2. Maybe create some unified interface to be implemented by classes that are stored?
3. New gui implementation
3.1. Using JavaFX
3.2. MVC / MVP design pattern?
4. New maven solution for external dependencies
4.1. Artifactory server?
4.2. Stored on github using [this](http://stackoverflow.com/questions/14013644/hosting-a-maven-repository-on-github/14013645#14013645) ?
5. Coding standards for following sprints 
5.1. [SonarLint ](http://www.sonarlint.org/)?
5.2. [Codebeat](https://codebeat.co/projects/github-com-technionyp5777-smartcity-accessibility), as in requiring some minimum score to be achieved
5.3. Warning level (Possibly jenkins build failure on warnings)
5.4. Decide on a minimal code coverage to be achieved
5.5. Tests standardization with mocking and DI
5.5.1. Test categories to differentiate gui tests from unit tests
5.5.2. Maximum time for any *single* unit test

Feel free to edit this post to add more points, or comment with your own
@Kolikant @yaelAmitay @koralchapnik @ArthurSap

**Comment by yaelAmitay** [comment]
1. We need to discuss using "map segment" in the reviews of **streets** and in searching.
the problem is that the navigation works in resolution of segement of the map. meaning that If you do not want the route to pass at some point you will have to avoid the whole segment of the map that include this point. there it'll make more sense that the reviews of the streets and the searching of streets will be on the whole segment and not on some specific point.
2. Another importantissue from last semester is picking the points in the map. Right now the user can pick any point in the map. it's diffןcult for him to choose the same point twice because he has to pick the exact same point in the map. A solution to this problem relate to (1) (from this comment) and to smart GUI.
3. we also need to make some major refactoring to some files in the project to make them more readable.

**Comment by Kolikant** [comment]
you guys already put up most of the points that we all brought up today. other than that I think there were:
1. there is the issue of the program not consistently working. which we should set as a priority.

2. the reason we even allowed users to put their own waypoints was for them to add locations to the map. so integrating locations and user input in the DB and choosing that interface of adding and viewing these locations. we need to discuss what is in their power and how it should look, also if and how privilleges work.

3. with the discussion I brought up of changing the atomicity  of search to be with navigation maps segments rather than what was my previous attempt, we need to maybe change the location's interface as to differentiate from streets and facilities. so the location interface should change.

4. another thing was search querirs which took a special effort to be allowed to be saved as part of user information. ned now to interface ways to view these queries, delete or anything else. these queries can and are saved with the user but so far not being used otherwise.

5. I think, although it is pretty much close, just try and think if we may want any new types of users. we implemented the rings of privileges to allow for easy changes, but we should talk if any other user privellege is needed, that after we discuss everything else and have a clearer view of the system.

6. JxMap's functionality is being wrapped by our own class. maybe discuss what more is needed in that class
