### ISSUE TITLE
Changing the calculation of BestReviews

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#222]
In the previous semester the calculation of the best n reviews worked as follows:
assume the number of pinned reviews is x.
if n <= x then we calculate is by average of the x reviews.
if n > x then we calculate the rating by average the pinned reviews and the best n-x unpinned reviews.

Do you think we should change this calculation and instead of using average to consider the activity and reliability of the user? (i.e to add each user some level tells how much we trust his review based on his activity in our application)
@KaplanAlexander @yaelAmitay @ArthurSap @Kolikant

**Comment by kapalex** [comment]
As we agreed during the meeting, considering user activity in the calculation sounds like a good feature to add

**Comment by yaelAmitay** [comment]
I thing it's a good feature, We also talked about considering the amount of likes of each review in the calculation.

**Comment by Kolikant** [comment]
this opens up a few new issues to concern ourselves with. as we need to add information to our users and monitor their purpose. I will open the issues and sugest that now that user monitoring and information has been open for discussion, everyone should add what they think our social network requires (I'll edit in the numbers of issues to concern themselves with this) #225

**Comment by koralchapnik** [comment]
Ok, and I will take care of this feature, so assign me to the relevant issues you open

**Comment by Kolikant** [comment]
ended up just creating one big issue. it's hard to say how much work it would be, since complexing the calculation (which is used in --every search and navigation--) could force rethinking how the calculation is used in the first place. one thing is certain, we either have user_credibility field saved and periodicly updated, have the accessability calculation updated periodicly instead, or have both. it's all in #225, ned to see how much it slows work before a decision is made, but you asked to leave it to you
