### ISSUE TITLE
user helpfullness monitoring, logic

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#228]
#225

**Comment by koralchapnik** [comment]
an example of way to determine the behavior is how much likes the user's comments have

**Comment by koralchapnik** [comment]
**Right now the user helpfulness goes as follows:**
there is the Helpfulness class and each user contains an helpfulness object.
the helpfulness of a user is the average likes this user has on each of his comments with ceiling.
negative number indicating the average dislikes this user has on each comment.
the calculation of bestReviews goes as follows:

**for calculating the rating of a specific location we doe the following:**

guess there are only n reviews we should consider in the rating calculation.

- sort the pinned reviews and the unpinned reviews by the reviewer's helpfulness from the biggest to the smallest and if its equal there is a secondary sorting by the value of the rating

- if the pinned reviews is bigger than n then we will consider the first n reviews of the sorted pinned reviews.

- if the pinned reviews is smaller than n, say x, then we will consider the x pinned reviews and the first n-x reviews from the sorted unpinned reviews.

- after we have n reviews which we will consider at, the total rating will be Weighted mean of the rating while the weights are the users helpfulness, and reviews of users who have negative helpfulness will not be considered in the mean except if they are admins and then their helpfulness will be 1

**Comment by Kolikant** [comment]
Can you fo through hoq helpfullness is updated? When? Hoq this information reaches the db

**Comment by koralchapnik** [comment]
@Kolikant  - I don't really understand your question.
can you please explain what you mean ?

**Comment by Kolikant** [comment]
Can you go through how helpfullness is updated? When? How this information reaches the db

**Comment by koralchapnik** [comment]
Helpfulness is calculated by subtracting the total dislikes of the user's reviews from total likes of the user's reviews and divide the result of the subtraction in the number of the total reviews this user has. 
Each user contains an Helpfulness object. 
When the user gets a like or dislike on one of his reviews, his helpfulness object is updated so that the likes/dislikes fields are increased accordingly. 
Moreover,  when the user creates a new review, his helpfulness object is updated by increasing the number of reviews this user have. 
Whenever we want to calculate a rating of some location, we go over the locations reviews and compute helpfulness for each user who reviewed it. The helpfulness is compute by calling a method of the helpfulness object which each user contains,  which means that whenever a user get like or dislike to one of his reviews or the user creates a new review the database should be updated,  I. E.  the user's helpfulness object should be updated. 
I didn't do the actual updates till we will have the new implementation of the DB.

**Comment by Kolikant** [comment]
If whenever anyone likes or dislikes, you need to update the user objectand thus the db eventually, you will still need to make sure to tell the db to update when you change, for synchrony's sace

This is what we were unclear on inthe previous issue

**Comment by koralchapnik** [comment]
I need the DB's interface for the update

**Comment by Kolikant** [comment]
Its user manager who hasnt changed
I need to add the update and recreation of the object you have just created, but as i've said before, its update and login to update or get a user.
Look at old gui for example of usage, I will make sure to add the changes and figure out synchrony, just need that you make sure to update regularly
