### ISSUE TITLE
client side search for locations(simple search)

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#257]
the client should be able to search for a location by its address. 
the search request should go to our servers.

server side #258

**Comment by Kolikant** [comment]
this has proven surprisingly difficult and time consuming, as I was unable to use any service that I provided, yet since ionic needs all the client side to work (or else it just doesn't "compile") I refreined from commiting any of my work since those are quit binary and now they stand on 0 -> not working. I am going to reattempt my ussage of my server side soon, hopefull with more success than last week (which as mentioned...my work was unseen as I have not committed)

**Comment by yaelAmitay** [comment]
@Kolikant , Do you want some help?

**Comment by Kolikant** [comment]
address search now works as expected and yields the results
