### ISSUE TITLE
Removing Gui package

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#329]
Since we have completely moved to Ionic, the gui from previous semester is not needed anymore.
I'd like to remove it but JxMapsFunctionality seems to be highly dependent on it

Look over JxMapsFunctionality and see what is relevant to us for this semester (if any) and remove the rest so we can delete the gui package

**Comment by Kolikant** [comment]
Jxmaps is inherently coupled, though i don't think it should be a problem, but could we make the gui pakages deprecated rather than delete them? Just to maybe make removing all that work hurt less? That was pretty much half a semester of work that gui :(

**Comment by kapalex** [comment]
The problem with making it deprecated is that API changes require updating the GUI as well, which is time wasted
I've already had to make changes to it because it seemed inconvenient to delete from a separate branch, but now that we are on the master again i'd rather (with all the pain involved) remove it as quickly as possible to avoid further problems

**Comment by Kolikant** [comment]
That sucks, but you are right

**Comment by Kolikant** [comment]
well, except for pretty much having the mapView inside of it and the encapsulating of search so that serchers won't have to import all of jxmaps o search. it seems that most of my work in it was to encapsulate all the horrors you needed for adding stuff to the gui. none of which is used now in ionic. I'm leaving just what is and will refactor that soon as well.

**Comment by Kolikant** [comment]
you can delete the gui packages now

**Comment by kapalex** [comment]
Still can't, `OptionsWindow` is still used
Just delete it when you finish, that way you'll know its ready
