### ISSUE TITLE
Styling the app

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#333]
I will be responsible to change the styling of our app from the default ionic styling to another one using the css files.
Each page can have different layout determined by the author of the page, but the colors, buttons, background, logos etc should remain consistent between pages.

**Comment by koralchapnik** [comment]
Related links: 
https://github.com/zachfitz/Ionic-Material
https://www.joshmorony.com/using-the-web-animations-api-in-ionic-2/

**Comment by kapalex** [comment]
I would suggest trying to stick to as much of an android feel as possible, both because of its consistency and because android is our main target
The official material design guidelines can be found [here](https://developer.android.com/design/material/index.html)

This would mean our design will will mostly stick to a few basic colors (main and accent) which can be picked our using [this](https://www.materialpalette.com/blue/teal) nifty site 

Icons can be obtained from [here](https://materialdesignicons.com/)

and some stock photos can be found [here](https://www.pexels.com/)

_note that all of these resources are free use, with no attribution required which is fantastic, do check for each specific item you use it doesn't have some license attached that says otherwise_

I would also suggest using the default android font, as it both looks good (and official), and again - consistency.

**Comment by kapalex** [comment]
I'm trying to unify the pages under some design scheme, look at the main page and the map, what do you think ? @Kolikant @koralchapnik @ArthurSap @yaelAmitay  (advised to install on an android device)

**Comment by koralchapnik** [comment]
looks good. so just to make sure, the colors of our app are blue and orange ?

**Comment by kapalex** [comment]
Unless anyone objects to it, then yeah

**Comment by koralchapnik** [comment]
ok, so i'll change the colors in the admin page accordingly cause I've added it some css style

**Comment by kapalex** [comment]
If you can (and this relates to everyone) copy the navbar from the main page to your pages as well, so we have a consistent one (with the name of the page different of course)
