### ISSUE TITLE
Save reviews in the database

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#35]
Create and save user's reviews in specific database

**Comment by ArthurSap** [comment]
In regards to issues #32 , if the admin wants to delete a review, should we completely remove the review from the DB, or store it somewhere else in case we might need to restore it?

**Comment by Kolikant** [comment]
Completely remove it

**Comment by kapalex** [comment]
possible idea for the future to let the admin "hide" reviews from regular users, but still be able to see it himself, and restore later

**Comment by Kolikant** [comment]
The reviews represent ones in thousands of reviews by users.
Removing reviews meens getting rid of garbage or spam.
Saving it to the side seems irrelevant

We assume that the admin knows what he is doing, removing only what is garbage.

**Comment by kapalex** [comment]
Assuming a review said something controversial, for example if a review stated some place doesn't offer a service that other reviews claim it does, an admin could hide the review until he will authenticate the information

**Comment by Kolikant** [comment]
Rather than hide it
Add an "awaiting authentication" apliable by the admin

**Comment by yossigil** [comment]
Good job @yaelAmitay  (well defined issue)

**Comment by ArthurSap** [comment]
@Kolikant , @KaplanAlexander If there's a spam review (say an ad or a "sdfsdkngsd" kind of reviews) the admin will completely remove this review from the DB, otherwise the admin can either hide it, or move it to another DB (said reviews can be automatically removed from the system after a while).
What do you think?

**Comment by kapalex** [comment]
For a start probably just deleting, later on moving it to another DB (specificaly for parse server, if reviews are stored in "Review" class then we can move them to "ReviewHidden" class easily) as an option of hiding seems like a good solution

**Comment by ArthurSap** [comment]
Should a review's initial status be hidden? When a user posts a review should it:
a. stay hidden until its approved by an admin 
or
b. be posted normally and then hidden by admin in case of need
problems I see:
a. not scalable - I don't see how admins can confirm reviews that are posted by the thousands.
b. spam all over - same problem as ^, doubts admins could handle it

Maybe start with solution a (since we do not expect many reviews) and then integrate some automatic filtering system?

**Comment by kapalex** [comment]
At this point i think option B fits best
as a solution for the spam problem we can implement features of banning users and such in the next sprint,  and hopefully that will be suffiecient

**Comment by Kolikant** [comment]
The assumptionis that the social network is self correctong for the most part.
Bad reviews would be disliked and not seen in the calculation of the best reviews.
Admins needhave extra power for the rare occations that interveening is needed.

All actions must be independent of the admins, the admins can do anything. Those arethe guidelines

So, b is the best option since admin would delete just spam that needs be removed while most of it will justbe disregarded by the social network.

**Comment by assaflu** [comment]
Is there any reason a certain review wouldn't be saved, or should all reviews be saved?

**Comment by assaflu** [comment]
what do you say if instead of having a user in the review class we will only save the userName? @Kolikant @koralchapnik

**Comment by koralchapnik** [comment]
Is having a user does complicate things belong to you?  If it is,  I can do
the necessary things now..

**Comment by Kolikant** [comment]
Its fine by me, assaf

**Comment by koralchapnik** [comment]
So to change it?

**Comment by kapalex** [comment]
ReviewManager doesn't seem to be storing the list of ReviewComments, just the review itself
 @assaflu

**Comment by ArthurSap** [comment]
Review class saves the user as a string (saves its name) - there is a default c'tor for User (or at least AuthenticatedUser) - which doesn't contains a string (hence user.getString() == null).
1) I fixed that and added a default user name for that c'tor. Please look over it.
2) Why do we save users in Reviews as user name (string) and not the user itself (User.class)?

**Comment by Kolikant** [comment]
Parse user doesnt allow elaborate types to be saved.
User name is a good enough identifier, as we maintain only ine user per username

**Comment by Kolikant** [comment]
Do you need me to create a method that returns a user of a given name?

**Comment by assaflu** [comment]
finished the issue if there are changes to do reopen it
