### ISSUE TITLE
Question about using mapquest

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#38]
As I suggest in the wiki page in solution number 3(https://github.com/TechnionYP5777/SmartCity-Accessibility/wiki/Team-Navigation-Meeting) we can use the service mapquest. 
https://developer.mapquest.com/products
this service provide simple REST API for routing and using maps.

pros of using this service:
- the service does exactly what we need. It allows us to get routes from location A to location B. More important it allows us to avoid streets with simple request to their servers.

cons of using this service:
- It does exactly what we need so wo won't have much to do in the project...
- This service cost money for using over 15000 transactions per month

**Comment by kapalex** [comment]
I think the best solution is to use 3 as the solution for navigation, while still using JxMaps  as the general map service api.

JxMaps offers the entire gui solution we require in addition to support for google maps api search queries.
Since it does not offer a solution to navigation issue while avoiding routes, for this specific issue of navigation we can call an external api (MapQuest)

MapQuest can get us a navigation route from point A to point B while avoiding "links", link ids we can get from the api with a lat lng coordinate - which we can get from JxMaps

Meaning the way navigation would work with both api : we take coordinates from JxMaps of locations we want to avoid (not accessible routes) and get their link ids from MapQuest, then we get a navgation route from map quest that avoids those links, which we can translate to JxMaps again by coordinates.

The bulk of the work here would be translating the response from Map Quest.
Assuming (and it does seem so) it doesn't have a Java client, that means translating a response from the REST API of map quest to a route on our map.   Which is alot of work, but we might be able to get some of it by exploring the android client.

The cost shouldn't be a problem as it is an academic project for now, and we shouldn't be getting a lot of users as of yet, so 15000 transaction per month should do just fine.

**Comment by yaelAmitay** [comment]
But, it means that all we are going to do is use REST requests. The navigation was supposed to be our main logic in the project.
In addition we are limiting our possibilities to add features to the navigation in the future, because we can't provide to our client something that MapQuest isn't providing.
Therefore i think we should use solution number 2.

**Comment by kapalex** [comment]
I'm not sure I fully understand solution number 2.
Would it require (in the long run) to transform the entire map to our own?
Doesn't that seem redundant for the project we are attempting to achieve to have its own map ?(even if we will only develop a POC map)
Personally I think this solution will require even more work that isn't directly related to out project than solution 3, and that doesn't seem like the right idea in my opinion

**Comment by yossigil** [comment]
Good discussion

**Comment by yaelAmitay** [comment]
Yes, it means we are going to save our own version of the map, we can still use JXMap for the GUI and getting locations from the user.
I don't think it's unusual for the Smart City to own it's own copy of the map. 
And  as I said I really don't think we should limit ourself this way.
Maybe we should consult with the advisors.

**Comment by kapalex** [comment]
About limiting our future options : the main feature of the project isn't navigation, but providing an environment where people can share information (the social network part of the project).
Navigation is just another feature we want to add to our project, and it seems that requiring its own map is a hefty price to pay for one feature (thinking beyond the POC stage, an entire global map is a project in its own right)
Before we go to the mentors, it would be great to get some more opinions from the rest of the team @Kolikant @koralchapnik @assaflu @ArthurSap

**Comment by yaelAmitay** [comment]
We don't need the map of eveything, we just need the map of the city. We are developing a program for the SmartCity. We only need the map of the city. It should not be that massive.
BTW it seems like we disagree about the main idea of our project lol.

**Comment by kapalex** [comment]
Yes - a map of the city. For EVERY city (again, after the POC stage).  That is massive.
And it seems we (as a team) chose navigation to be one of least important features in the use cases we defined in the project [here](https://github.com/TechnionYP5777/SmartCity-Accessibility/projects/1)

**Comment by yaelAmitay** [comment]
Well fine then. We will use option 3 as the solution.

**Comment by yossigil** [comment]
:+1:

**Comment by koralchapnik** [comment]
I agree with you.  
Option 3 seems to be the best one.
