### ISSUE TITLE
Integrate with openid

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#43]
Decided to use opeid for authentication, need to integrate with it #34

**Comment by Kolikant** [comment]
http://openid.net/specs/openid-connect-session-1_0.html

**Comment by Kolikant** [comment]
https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions

**Comment by Kolikant** [comment]
https://www.youtube.com/watch?v=i1datiYVDVc

**Comment by Kolikant** [comment]
https://www.youtube.com/watch?v=YLHyeSuBspI

**Comment by Kolikant** [comment]
it might just be me, but it seems I am having difficulty integrating with openId. Should I press on or would it be best to have minor authentication for the presentation in two weeks? @yossigil

**Comment by Kolikant** [comment]
https://www.youtube.com/watch?v=Kb56GzQ2pSk

**Comment by Kolikant** [comment]
https://www.youtube.com/watch?v=BdKmZ7mPNns

**Comment by Kolikant** [comment]
https://www.youtube.com/watch?v=io_r-0e3Qcw

**Comment by yossigil** [comment]
The basic rule is simple: Max output in minimal work. I am not sure how to translate it to your case.
If I were you, I would steal as much code as possible, to make openId, but I did not research this venue.
Make a decision, try to make the best decision, and be ready to explain your decision.

You do not have to be ready to explain your decision just because we will ask. Yes, we might ask. But the crucial point is different: you have to understand why you made a decision so that you can revoke it when necessary.

Explanation of a decision should not be long, but it should be more concrete than "we had some difficulties". Describe the difficulties in a way that others would know what they might be facing should they wish to revoke it.

@yh-github @AdiOmari @zvili @orimarco @idabran: you may want to cut and paste for similar cases.

**Comment by kapalex** [comment]
As an alternative, I'd like to add that Parse Server does offer authentication built in.
Meaning our existing server already offers a tool for authenticating users, and if we want to to "Max output in minimal work"  using an existing environment (with lots of code examples on how to use it) might be the best solution.
