### ISSUE TITLE
installations for camera and file use

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#430]
as part of enabling pictures upload in our app, some installations are required.
it might happen that if you pull the project now, the ionic will crash so please do the following:

- go into client side folder and open the cmd from it
 

- if you don't have Android Studio, install it.

- add a environment variable called ANDROID_HOME and set it to be the android sdk installation.

- add to the PATH the path to 'tools' and 'platform-tools' folders inside the sdk folder

- run the following commands from the cmd:
      `cordova platform add android`
      `cordova plugin add cordova-plugin-camera`
      `cordova plugin add cordova-plugin-file`
      `npm install @ionic-native/camera --save`
      `npm install @ionic-native/file --save`

as Alex use to do, mark if you've done that and unassign yourself:

- [x] Ariel

- [x] Arthur

- [x] Alex

- [x] Yael

**Comment by Kolikant** [comment]
having dificulties 
![image](https://user-images.githubusercontent.com/23051198/27100486-fb204962-5086-11e7-81f2-47c056fce476.png)

**Comment by koralchapnik** [comment]
It's OK you can keep on

**Comment by Kolikant** [comment]
![image](https://user-images.githubusercontent.com/23051198/27100701-9e0148f2-5087-11e7-9cd1-ce6e96b4f5e8.png)

 I probably  missed something.
can you go into more detail in the second and third steps ?

add a environment variable called ANDROID_HOME and set it to be the android sdk installation.
(I have android studio, but there is no sdk installation in it) 
![image](https://user-images.githubusercontent.com/23051198/27100758-d12eb9c6-5087-11e7-8a08-10fd5847c9a3.png)

add to the PATH the path to 'tools' and 'platform-tools' folders inside the sdk folder
(since I don't have an sdk folder, I couldn't do this either)

**Comment by koralchapnik** [comment]
When you installed the android studio you have also installed android sdk

**Comment by Kolikant** [comment]
took a long time to find. so putting here for future users:
C:\Users\[your name]\AppData\Local\Android\sdk1

**Comment by Kolikant** [comment]
I did everything and have the same problem.
added here: 
![image](https://user-images.githubusercontent.com/23051198/27102128-d50b52fc-508c-11e7-9a5e-bbaaa82ca86f.png)

and here:
![image](https://user-images.githubusercontent.com/23051198/27102140-e1155660-508c-11e7-9bda-1a9990c9a9f9.png)

**Comment by Kolikant** [comment]
here is the solution. someone (a saint by my opinion) made library for this. run

* npm install -g npm-install-missing
* npm-install-missing
