### ISSUE TITLE
About adding queries

### ISSUE THREAD

**Issue by koralchapnik** [TechnionYP5777/SmartCity-Accessibility#446]
Hi, in the user page there is option to add queries and implement them.
but when pressing the button of the query i've added or the edit, there is popup massage says that it still not implemented.
Is it going to be implemented? cause this is the only thing in the user page right now and you are on vacation till the end of the semester.
If it is not going to be implemented, the user photos will be the only feature in this page, which makes it littlte useless.

**Comment by koralchapnik** [comment]
Moreover, when adding search query, you should search it to check if it is a valid address so the user could navigate to it.

**Comment by Kolikant** [comment]
As i've explained i believed it having the buttons to show how the oage should look would be the top priority if i wasn't able to finish the functionality .

Being atuck on just opening the search in mapview made it so i wasn't able to finish functionality as one part was missing

So rather than have buttons that don't look like they do anything though they do everything but the final step, i printed an error message

Adi said itbetternot to haverhebuttons at all so they are commented out

But were someone not on pagra to put them back (except the edit button, that one was there just tolookgood,no issue about editing queries)

**Comment by Kolikant** [comment]
Then she / he would have just one thing to finish for the queries ro work

And would probably need to deletethe edit button aince thwy existed back when i thought it was better to haveunimplemented buttons than no buttona at all

**Comment by kapalex** [comment]
Note that this was actually done by me in #452, and seems to work quite well

**Comment by Kolikant** [comment]
Oh cheers mate! Good job

**Comment by Kolikant** [comment]
You are the Zismaier to my Mozart
