### ISSUE TITLE
create Special Ratings for Admins usage

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#48]
admin should be able to effect what the best reviews are.
to be considered:
1) be allowed to set ratings of reviews to max, ensuring they will be considered
2) having a special "admin approved" token marking it to be queried by the user or disregared
3) making it the only legal review of a location, meaning that we could have some locations only under admin juresdiction should they deem it to be so.

opinion?
@KaplanAlexander  @yaelAmitay  @ArthurSap  @assaflu @koralchapnik

**Comment by ArthurSap** [comment]
@Kolikant are the pin and un-pin actions enough? Do we want more behavior?
I think that locking specific locations should be done in the next sprint but we can do it now with the following proposal:
Add a field to Location class: isLocked - true iff location is locked to admins' reviews only.
If the field is true, refer only to pinned reviews list (since admins' reviews are automatically pinned).
Problems/questions:
Do we want to prevent regular users from writing reviews too (or simply just not show them)? If so, I think we should push this option (locking locations for reviews by admin only) to the next sprint - unless you have a good idea on how to do that.

**Comment by koralchapnik** [comment]
I think it should be done in the next sprint.  
Why would we want prevent from regular users to write reviews too?  That is all the meaning of social network..

**Comment by ArthurSap** [comment]
It was brought up in a meeting but I really don't know why..

**Comment by Kolikant** [comment]
Next sprint meens nexy semester,
Which is fine by me if you deem it so

**Comment by ArthurSap** [comment]
So I'm closing this issue.
Next semester we will open a new issue just for that mission.
