### ISSUE TITLE
rethinking the design of admin

### ISSUE THREAD

**Issue by Kolikant** [TechnionYP5777/SmartCity-Accessibility#67]
It was pointed out by @yossigil here #39 that we should rethink our design of admins.
That having an admin class is not scalable and that we should instead have a privilege level, checked by the methods, as to gain different behavior.

do you think that it would be something we will manage to change? what could be effected by it?

@ArthurSap

**Comment by ArthurSap** [comment]
I fail to see the point in more than 3 privilege levels (default, registered and admin) - perhaps there is a point in promoting the registered user to an admin (not that I see why we would do that). Won't just re-creating a new admin from that user (i.e public Admin promote(User u)) be enough for that?

**Comment by Kolikant** [comment]
I agree with you actually. I guess I misunderstood. the example yossi gave was about  having levels and having promotions which is not something we intend, so we should be fine

**Comment by yossigil** [comment]
:+1:

**Comment by kapalex** [comment]
For the sake of this argument lets assume we might want to add another privilege level sometime in the future (which we might, for example a "moderator" who can hide reviews but cannot delete them, or cannot ban users like an admin can) and if we do our current design won't be able to cope very well.

Problems with the current design -

1. The current field in the parse server that differentiates admin and user is a boolean, as soon as we have 3 classes that won't work.  Changing a field type  in the database might be a problem depending on the point we decide to add the third privilege level (incompatibility)
2. The way we recognize an admin both in communication with the database (saving and restoring) and when communicating with the GUI (user should only see buttons relevant to him, for example a regular user shouldn't be able to see a 'delete' button on a review that isn't his) requires checking the class of the user object, which is a very bad scalability wise (requires an additional check for every new class we add) and is prone to errors (forgot to check the new class at some point in the code...)
3. Ideally we would like to be able to do some changes in the software  without changing the code (thinking of the point where we already publish the application, that means not requiring a new version release that everyone has to update to), the current design won't allow it of course since we need new classes, even in the case we don't actually add functionality (same example, a moderator only has some of the abilities of admin, no new abilities)

An alternative design (based on suggestions from yossi) -

We create only a single class for user (some separation between functionality and data storage may be in order)  that has an int field `privilege`. We add flags such as 
- `WRITE_ACCESS =1 `
- `READ_ACCESS = 2`
- `DELETE_ACCESS = 4`
- `BAN_ACCESS = 8`
- etc.


and set the user privileges to be `(FLAG1 | FLAG2 | FLAG3)`
for example  - 
- default user gets `READ_ACCESS `
- signed in user gets `READ_ACCESS | WRITE_ACCESS`
- admin gets all of them...


And before we let a user do a task we check for the access level we require (`privilege & READ_ACCESS` for example)

This solves the problems provided earlier - 

1. Privilege level are true for all users, so database is consistent regardless of new classes
2. We don't need to check the class just the access level
3. If we have an admin function that sets user privileges (as we should with this design), we can set any privileges we want without actually changing the code.

In my opinion this would be a better design going forward.

Would like to hear your opinions 
@Kolikant @ArthurSap @koralchapnik @yaelAmitay @assaflu

**Comment by Kolikant** [comment]
I see your point.
It is more scalable
But, we assume that there is a very low number of admins; aka people with municipal authority.

It would make more logic to lay the way for a chande in case our intentions with what admins are are ill recieved or want change.
I agree with you then.

We haven't intended it to have those capabilites and have no intentions whatsoever to use them.... But the safe thing would be to allow to change our mind.

**Comment by Kolikant** [comment]
it's your call @ArthurSap , you are the one implementing it

**Comment by ArthurSap** [comment]
We haven't planned for our application to have large amount of admins or the need in several privilege levels that have more/less actions to.
I do not see the point in implementing it since the need for those comes from very large applications with very large user-base.
Sure, it would be more scalable and flexible if we were to develop Waze 2 but that would require time. Far more than one year (for 6 students). I don't believe we will ever reach the point in our project where we will need more than 2 (3 with default user) privilege levels hence these changes will result in waste of time and effort that can be invested in other places.
If you all decide we should go for it I personally think we should do a little variance on @KaplanAlexander 's idea to be more like the protection rings in linux's kernel:
e.g if 0 is the highest level and 5 is the lowest level and we want to enable action A for some privilege level, say 3, we could simply check if(User.privilege =< 3) do stuff; instead of READ_ACCESS | WRITE_ACCESS etc.
I vote against implementing these changes as I see them as a waist of time but I will go with the majority and do the work if decided so.

**Comment by yaelAmitay** [comment]
I think we need to find a design that enable us to make changes like that in the future.
One option is to do as @KaplanAlexander  suggested. But we don't have to implements all of this right now. we can leave it to the next sprint. My only problem with this idea is that it's not so OOP.
About @ArthurSap idea, I think that using the idea of the protection ring in linux could be a little confusing. flags seems to be the more understandable. And the implementation is kind of the same.

**Comment by ArthurSap** [comment]
@yaelAmitay More flags, more things to worry about. What if we want to add new privilege level? Add new flags, change a lot of code. What if we want to add a new action that requires certain amount of privilege? Add new flags, change a lot of code. What if we want to cancel someones privilege level/make an action require a higher/lower privilege level? would require a lot of changes in the code..

**Comment by yossigil** [comment]
Keep up the hearty discussion. But, note that you cannot go too wrong either way at this early stage

**Comment by yaelAmitay** [comment]
@ArthurSap, I understand your point of view. And I think that both solutions are too complicated.
I really think that simple inheritance is the best solution.

**Comment by Kolikant** [comment]
Which means changing nothing :)
