### ISSUE TITLE
Fix BrokenAdminTest.setUp

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#80]
Full output can be found here #73

**Comment by ArthurSap** [comment]
![image](https://cloud.githubusercontent.com/assets/15543389/21295184/01744b0c-c558-11e6-9677-c24e8da4ecd7.png)
The problem is in ReviewManager's upload method, I do not know how to fix it. I use it under the assumption it works and simply pass it a Review object (but it fails somewhere inside along the line).

**Comment by kapalex** [comment]
Transferred issue to @assaflu , problem seems to be with the types that are given in ReviewManager

**Comment by ArthurSap** [comment]
New problem - I think its more on your method now @KaplanAlexander (on $.save() the test flies).
![image](https://cloud.githubusercontent.com/assets/15543389/21471355/6cd0ab1a-cab8-11e6-9c52-6c0f8c3b909a.png)

**Comment by kapalex** [comment]
will check and report back

**Comment by kapalex** [comment]
I do see the build is not failing anymore, where is this error happening?

**Comment by Kolikant** [comment]
haven't you and alex solved this today at the meeting?

**Comment by kapalex** [comment]
yep
